go.mod, go.sum, pkg/cmd/importcmd/import.go, pkg/cmd/importcmd/import_deploy_integration_test.go, pkg/cmd/importcmd/import_github_action_integration_test.go, pkg/cmd/importcmd/import_gitops_repo_test.go, pkg/cmd/importcmd/import_golang_integration_test.go, pkg/cmd/importcmd/import_integration_test.go, pkg/cmd/importcmd/import_kube_resources_integration_test.go, pkg/cmd/importcmd/import_test.go, pkg/cmd/root/quickstart_integration_test.go, pkg/cmd/testimports/fakes.go
so that the BDD tests still work
=> fix: upgrade and auto trigger pipelines on create

pkg/cmd/root/root.go
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>
fixes #49
=> fix: set input to new input if nil

pkg/cmd/importcmd/import.go
as it may stop the project from being created
=> fix: don't modify the git organisation name

go.mod, go.sum, pkg/cmd/importcmd/import.go, pkg/cmd/importcmd/import_tekton_catalog_integration_test.go
so that we import the clean quickstart; wait for the lighthouse to be setup; then we push to git
=> fix: lets move the application of the build pack to later

pkg/cmd/importcmd/buildpacks.go, pkg/cmd/importcmd/import.go, pkg/cmd/importcmd/import_integration_test.go, pkg/cmd/importcmd/source_config_pr.go, pkg/cmd/root/quickstart_integration_test.go
so that we can properly determine what kind of scheduler we need to use in
the cluster git repository PR.
Then we do the commit + push after the PR is merged and the webhooks +
triggers are setup
=> fix: lets apply the build pack before the cluster PR

pkg/cmd/importcmd/import.go
Signed-off-by: Youssef El Houti <youssef.elhouti@gmail.com>
=> fix: projectname defaults to n on import

pkg/cmd/importcmd/import.go, pkg/gitresolver/buildpack_test.go
Ref: https://www.conventionalcommits.org
=> fix: conventional commit messages

pkg/cmd/importcmd/source_config_pr.go
as the PR pipeline will add the updatebot
=> fix: disable auto merge

pkg/cmd/importcmd/add_collabotor.go
=> fix: better defaults when trying to find boot secret

go.mod, go.sum, pkg/cmd/importcmd/import.go
and add a bit more diagnostics
=> fix: lets make sure we don't have empty poll period

pkg/cmd/importcmd/input.go
=> Update error message on git failure

.gitignore, pkg/cmd/importcmd/add_collabotor.go
Gitea doesnt support the invitation api, so dont call ListInvitations or AcceptInvitation
=> Gitea dont use invitation api

Makefile
to avoid the release pipeline breaking
=> fix: add a separate release goal

README.md
Fixes https://github.com/jenkins-x-plugins/jx-project/issues/423
=> docs: Remove references to alpha

README.md, pkg/cmd/importcmd/import_tekton_catalog_integration_test.go, pkg/cmd/root/mlquickstart.go, pkg/cmd/root/mlquickstart_integration_test.go, pkg/cmd/root/root.go, pkg/cmd/testimports/fakes.go, pkg/quickstarts/load.go
Signed-off-by: Terry Cox <terry@bootstrap.je>
=> feat: Upgrade MLOps support for v3 compatibility

go.mod, go.sum, pkg/cmd/importcmd/import.go, pkg/cmd/importcmd/import_bad_name_integration_test.go, pkg/cmd/importcmd/test_data/import_projects/docker_slave_18.04/main.go
if a repo name has a bad character, like dot, lets pass it along to the `jx
pipeline wait` command as is
=> fix: add test and fix for handling repos with bad characters

pkg/cmd/importcmd/pack.go
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>
=> fix: perm issues when creating pack folders

pkg/cmd/importcmd/import.go
=> fix: Only update name of chart

pkg/cmd/importcmd/input.go
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>
=> fix: change wording in warning to show scm other than github

go.mod, go.sum
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>
=> fix: bump go-scm to fix issues with bb cloud quickstart

Makefile, pkg/cmd/root/spring.go, pkg/spring/model.go
Fixes that `jx project spring` with default options creates an application that won't build.
=> fix: Create spring project with gradle
